### ISSUE TITLE
archlinux, python2.7 not work for `buildtins.__import__(name)` in line 106

### ISSUE THREAD

**Issue by neo5simple** [ros-visualization/python_qt_binding#28]
followed ROS wiki installation for Archlinux, almost goes well. but when I try call

```bash
rosrun rqt_graph rqt_graph
```

got `AttributeError: 'module' object has no attribute '__import__'`

finally I found my Python2.7.11 work fine with `__builtin__`, but the try-except in `binding_helper.py` has  no exception for this `import builtins`. I'm not a python programmer, so just comment it, and add import line manually.

**Comment by dirk-thomas** [comment]
Can you please:
* clarify which exact version you are using
* post the exact error message including line numbers to ensure
* show the diff of changes you made to make it work for you

**Comment by neo5simple** [comment]
I'm so sorry about the description unclearly, because of the installation all from `yaourt` -- a package manager.

1. git clone from tag=release/jade/python_qt_bindding/0.2.16-0
2. when I run sort of `rqt` or `rqt_graph`, the error:

```
Traceback (most recent call last):
  File "/opt/ros/jade/bin/rqt", line 13, in <module>
    sys.exit(main.main())
  File "/opt/ros/jade/lib/python2.7/site-packages/rqt_gui/main.py", line 59, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider, plugin_manager_settings_prefix=str(hash(os.environ['ROS_PACKAGE_PATH'])))
  File "/opt/ros/jade/lib/python2.7/site-packages/qt_gui/main.py", line 336, in main
    from python_qt_binding import QT_BINDING
  File "/opt/ros/jade/lib/python2.7/site-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/ros/jade/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 266, in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
  File "/opt/ros/jade/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 85, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/jade/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 140, in _load_pyqt
    _named_import('PyQt4.%s' % module_name)
  File "/opt/ros/jade/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 107, in _named_import
    module = builtins.__import__(name)
AttributeError: 'module' object has no attribute '__import__'
```

3. What I done:

```diff
@@ -30,10 +30,11 @@
 # ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-try:
-    import builtins
-except ImportError:
-    import __builtin__ as builtins
+# try:
+    # import builtins
+# except ImportError:
+    # import __builtin__ as builtins
+import __builtin__ as builtins
 import os
 import sys
```

**Comment by dirk-thomas** [comment]
Please try if the problem still exists in the latest release: 0.2.17.

**Comment by neo5simple** [comment]
It works for me, many thanks.
